[package]
name = "gaudi"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.8"
prost = "0.11"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
prost-types = "0.11.5"

[build-dependencies]
tonic-build = "0.8"
